### ISSUE TITLE
Platform and Windowing Refactor

### ISSUE THREAD

**Issue by maluoi** [StereoKit/StereoKit#703]
## Motivation

StereoKit's platform code initially started as Windows only with OpenXR + Simulator, and has since grown to be Windows, UWP, Android, Linux, Web, OpenXR, Simulator, and kinda more. The original architecture was okay early on, but needs some adjustment in order to reduce redundant code, add more XR backends, and flesh out platforms without creating code with low test coverage.

This refactor focuses on creating a platform agnostic windowing abstraction, so that XR backends can own the windows and their input events, instead of the platforms. This means the Simulator XR backend can create or use a flat window for display, OpenXR can create a window for input and mirroring, and headless can skip creating a window entirely! This also helps consolidate the top level rendering code into a single location, in preparation for better MSAA, and post-processing effects.

## Tasks

Work on this refactor is happening in the [feature/window_refactor](https://github.com/StereoKit/StereoKit/tree/feature/window_refactor) branch.

- [x] Win32 windowing abstraction.
- [x] Win32 works with simulator.
- [x] Win32 works with OpenXR.
- [x] UWP windowing abstraction.
- [x] UWP works with simulator.
- [x] UWP works with OpenXR.
- [x] Linux windowing abstraction.
- [x] Switch Linux to EGL. (GLX has an inverted window/device ownership scheme)
- [x] Linux works with simulator.
- [x] Linux works with OpenXR.
- [x] Android windowing abstraction.
- [x] Android works with simulator.
- [x] Android works with OpenXR.
- [x] Web windowing abstraction.
- [ ] Web works with simulator.
- [ ] Web works with OpenXR.
- [x] Implement headless mode.
